"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const warrior_js_1 = require("./src/warrior.js");
const mage_js_1 = require("./src/mage.js");
const archer_js_1 = require("./src/archer.js");
const wraithKing = new warrior_js_1.Warrior('Папич', 50);
const darkWillow = new mage_js_1.Mage('Вилка');
const mirana = new archer_js_1.Archer('Мирана', 15);
console.groupEnd();
console.group('ПАПИЧ');
wraithKing.takeDamage(90);
wraithKing.heal(30);
wraithKing.levelUp();
console.groupEnd();
console.group('МИРАНА');
mirana.shoot();
mirana.levelUp();
mirana.restockArrows(5);
console.groupEnd();
console.group('ВИЛКАЧНОСТЬ');
darkWillow.castSpell(65, 'реалм');
darkWillow.castSpell(70, 'бедлам');
darkWillow.levelUp();
darkWillow.castSpell(65, 'реалм');
console.groupEnd();
console.group('Ошибки');
wraithKing.name = '';
darkWillow.health = 400;
console.groupEnd();
//# sourceMappingURL=main.js.map